
export const  AGREEMENT_FETCH_REQUEST='AGREEMENT_FETCH_REQUEST'   
export const  AGREEMENT_FETCH_SUCCESS='AGREEMENT_FETCH_SUCCESS'   
export const  AGREEMENT_FETCH_FAILURE='AGREEMENT_FETCH_FAILURE' 

export const FILTER = 'FILTER';


